<a href="https://colab.research.google.com/github/C026-01-0774-2023-NewtonOlando/football/blob/main/premier_league.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import kagglehub

# Download latest version
path = kagglehub.dataset_download("siddhrajthakor/premier-league-table-202526")

print("Path to dataset files:", path)

Downloading to /root/.cache/kagglehub/datasets/siddhrajthakor/premier-league-table-202526/21.archive...

100%|██████████| 9.18k/9.18k [00:00<00:00, 4.07MB/s]

Extracting files...
Path to dataset files: /root/.cache/kagglehub/datasets/siddhrajthakor/premier-league-table-202526/versions/21

In [17]:
import os

dataset_path = "/content/drive/MyDrive/Premier_League_Model/datasets"

print(os.listdir(dataset_path))

[]

In [26]:
!rm -rf /content/drive

In [27]:
from google.colab import drive

drive.mount('/content/drive')

Mounted at /content/drive

In [28]:
import os

print(os.listdir('/content/drive/MyDrive'))

['Colab Notebooks', 'AUD-20250206-WA0038.mp3', 'ac.human', 'Document from Dope Alfredo (1)', 'Document from Dope Alfredo', 'killerBee X Dope Alfredo - Drip (mastered).wav', 'All.pdf', 'original.pdf', 'December styled.pdf', 'December.pdf', 'heal(6th of pain album).pdf', 'pretty eyes.pdf', 'rollercoaster.pdf', 'rap as money.pdf', 'not trying.pdf', 'uko nami.pdf', 'Untitled document (49).gdoc', 'Mckayla\tTurpin.gdoc', 'Wulutee\tCapuzzi (1).gdoc', 'Edward\tRubio.gdoc', 'Leslie\tMaurin.gdoc', 'Selene\tMartinez.gdoc', 'Sam\tPearson.gdoc', 'Zachary\tHill.gdoc', 'Alejandra\tPerez.gdoc', 'James\tCole.gdoc', 'Gloria\tRomero.gdoc', 'Untitled document (48).gdoc', 'Untitled document (47).gdoc', 'Untitled document (46).gdoc', 'AMBER\tSNYDER.gdoc', 'Pdf .pdf', 'invoice ya leo .pdf', 'Samantha\tRodriguez.gdoc', 'CHRISTOPHER\tTAYLOR.gdoc', 'THOMAS\tOCHYLSKI.gdoc', 'Untitled document (45).gdoc', 'JACOB\tJOHNSON.gdoc', 'AMANDA\tCUBBAGE.gdoc', 'RACHEL\tSIEVERS.gdoc', 'Casandra\tWilkinson.gdoc', 'ANDREW\tFOLLMANN.gdoc', 'SAMUEL\tKING.gdoc', 'KYLE\tMADDEN.gdoc', 'HANNAH\tPARK.gdoc', 'Untitled document (44).gdoc', 'Untitled document (43).gdoc', 'MARVIN\tPEREZ VELASQUEZ.gdoc', 'JILLIAN\tVALENTINE.gdoc', 'Untitled document (42).gdoc', 'Untitled document (41).gdoc', 'Untitled document (40).gdoc', 'Untitled document (39).gdoc', 'NICHOLAS\tHANIGAN.gdoc', 'Untitled document (38).gdoc', 'Untitled document (37).gdoc', 'Untitled document (36).gdoc', 'Untitled document (35).gdoc', 'Untitled document (34).gdoc', 'Untitled document (33).gdoc', 'Untitled document (32).gdoc', 'Jake\tGorzek.gdoc', 'Untitled document (31).gdoc', 'Untitled document (30).gdoc', 'Untitled document (29).gdoc', 'Untitled document (28).gdoc', 'Untitled document (27).gdoc', 'Untitled document (26).gdoc', 'Untitled document (25).gdoc', 'Untitled document (24).gdoc', 'Untitled document (23).gdoc', 'Untitled document (22).gdoc', 'Untitled document (21).gdoc', 'Untitled document (20).gdoc', 'Untitled document (19).gdoc', 'Untitled document (18).gdoc', 'Untitled document (17).gdoc', 'Untitled document (16).gdoc', 'Untitled document (15).gdoc', 'Untitled document (14).gdoc', 'Untitled document (13).gdoc', 'Untitled document (12).gdoc', 'Untitled document (11).gdoc', 'Untitled document (10).gdoc', 'Untitled document (9).gdoc', 'Untitled document (8).gdoc', 'Untitled document (7).gdoc', 'Untitled document (6).gdoc', 'Untitled document (5).gdoc', 'Untitled document (4).gdoc', 'Jorge\tGarza.gdoc', 'Sam\tRocco.gdoc', 'Max\tHarry.gdoc', 'freak mp3', 'Sabrina\tPosada.gdoc', 'Wulutee\tCapuzzi.gdoc', 'Frank\tTurano.gdoc', 'Untitled document (3).gdoc', 'Untitled document (2).gdoc', 'Untitled document (1).gdoc', 'Ashley\tT Costello.gdoc', 'Johnna\tMulkey.gdoc', 'Weston\tBarnett.gdoc', 'Jose\tReyes.gdoc', 'Robert\tVasquez.gdoc', 'Sual\tRamirez.gdoc', 'Forcino.gdoc', 'Meghna.gdoc', 'Daniel\tDe La Cruz.gdoc', 'Robert\tNorton Iii.gdoc', 'Pedro\tRodriguez Beltran.gdoc', 'Untitled document.gdoc', 'Matthew\tJacobson.gdoc', 'Alana\tMadera.gdoc', 'Aaron\tMatassa.gdoc', 'Nargis\tRashid.gdoc', 'James\tFrancis.gdoc', 'Jordan\tMurray.gdoc', 'Tara\tKuhner.gdoc', 'Alessa\tPerkins.gdoc', 'Erica\tBowen.gdoc', 'ZHEN\tLI.gdoc', 'SUKANYA\tCHAKRABORTY.gdoc', 'Greg\tHerrera Jr.gdoc', 'cloud_performance_features.csv', 'Looking Through Good & Bad Examples.mp4', 'Premier_League_Model', 'download_copy.pdf']

In [29]:
project_path = "/content/drive/MyDrive/Premier_League_Model"

print("Project exists:", os.path.exists(project_path))

if os.path.exists(project_path):
    print(os.listdir(project_path))

Project exists: True
['datasets']

In [30]:
historical_path = "/content/drive/MyDrive/Premier_League_Model/data/historical"

print("Historical folder exists:", os.path.exists(historical_path))

if os.path.exists(historical_path):
    print(os.listdir(historical_path))

Historical folder exists: False

In [31]:
import os

datasets_path = "/content/drive/MyDrive/Premier_League_Model/datasets"

print("Datasets folder exists:", os.path.exists(datasets_path))

if os.path.exists(datasets_path):
    print(os.listdir(datasets_path))

Datasets folder exists: True
['2122.csv', '2223.csv', '2324.csv', '2425.csv', '2526.csv']

In [40]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [43]:
import os

print(os.listdir('/content/drive/MyDrive'))

['Colab Notebooks', 'AUD-20250206-WA0038.mp3', 'ac.human', 'Document from Dope Alfredo (1)', 'Document from Dope Alfredo', 'killerBee X Dope Alfredo - Drip (mastered).wav', 'All.pdf', 'original.pdf', 'December styled.pdf', 'December.pdf', 'heal(6th of pain album).pdf', 'pretty eyes.pdf', 'rollercoaster.pdf', 'rap as money.pdf', 'not trying.pdf', 'uko nami.pdf', 'Untitled document (49).gdoc', 'Mckayla\tTurpin.gdoc', 'Wulutee\tCapuzzi (1).gdoc', 'Edward\tRubio.gdoc', 'Leslie\tMaurin.gdoc', 'Selene\tMartinez.gdoc', 'Sam\tPearson.gdoc', 'Zachary\tHill.gdoc', 'Alejandra\tPerez.gdoc', 'James\tCole.gdoc', 'Gloria\tRomero.gdoc', 'Untitled document (48).gdoc', 'Untitled document (47).gdoc', 'Untitled document (46).gdoc', 'AMBER\tSNYDER.gdoc', 'Pdf .pdf', 'invoice ya leo .pdf', 'Samantha\tRodriguez.gdoc', 'CHRISTOPHER\tTAYLOR.gdoc', 'THOMAS\tOCHYLSKI.gdoc', 'Untitled document (45).gdoc', 'JACOB\tJOHNSON.gdoc', 'AMANDA\tCUBBAGE.gdoc', 'RACHEL\tSIEVERS.gdoc', 'Casandra\tWilkinson.gdoc', 'ANDREW\tFOLLMANN.gdoc', 'SAMUEL\tKING.gdoc', 'KYLE\tMADDEN.gdoc', 'HANNAH\tPARK.gdoc', 'Untitled document (44).gdoc', 'Untitled document (43).gdoc', 'MARVIN\tPEREZ VELASQUEZ.gdoc', 'JILLIAN\tVALENTINE.gdoc', 'Untitled document (42).gdoc', 'Untitled document (41).gdoc', 'Untitled document (40).gdoc', 'Untitled document (39).gdoc', 'NICHOLAS\tHANIGAN.gdoc', 'Untitled document (38).gdoc', 'Untitled document (37).gdoc', 'Untitled document (36).gdoc', 'Untitled document (35).gdoc', 'Untitled document (34).gdoc', 'Untitled document (33).gdoc', 'Untitled document (32).gdoc', 'Jake\tGorzek.gdoc', 'Untitled document (31).gdoc', 'Untitled document (30).gdoc', 'Untitled document (29).gdoc', 'Untitled document (28).gdoc', 'Untitled document (27).gdoc', 'Untitled document (26).gdoc', 'Untitled document (25).gdoc', 'Untitled document (24).gdoc', 'Untitled document (23).gdoc', 'Untitled document (22).gdoc', 'Untitled document (21).gdoc', 'Untitled document (20).gdoc', 'Untitled document (19).gdoc', 'Untitled document (18).gdoc', 'Untitled document (17).gdoc', 'Untitled document (16).gdoc', 'Untitled document (15).gdoc', 'Untitled document (14).gdoc', 'Untitled document (13).gdoc', 'Untitled document (12).gdoc', 'Untitled document (11).gdoc', 'Untitled document (10).gdoc', 'Untitled document (9).gdoc', 'Untitled document (8).gdoc', 'Untitled document (7).gdoc', 'Untitled document (6).gdoc', 'Untitled document (5).gdoc', 'Untitled document (4).gdoc', 'Jorge\tGarza.gdoc', 'Sam\tRocco.gdoc', 'Max\tHarry.gdoc', 'freak mp3', 'Sabrina\tPosada.gdoc', 'Wulutee\tCapuzzi.gdoc', 'Frank\tTurano.gdoc', 'Untitled document (3).gdoc', 'Untitled document (2).gdoc', 'Untitled document (1).gdoc', 'Ashley\tT Costello.gdoc', 'Johnna\tMulkey.gdoc', 'Weston\tBarnett.gdoc', 'Jose\tReyes.gdoc', 'Robert\tVasquez.gdoc', 'Sual\tRamirez.gdoc', 'Forcino.gdoc', 'Meghna.gdoc', 'Daniel\tDe La Cruz.gdoc', 'Robert\tNorton Iii.gdoc', 'Pedro\tRodriguez Beltran.gdoc', 'Untitled document.gdoc', 'Matthew\tJacobson.gdoc', 'Alana\tMadera.gdoc', 'Aaron\tMatassa.gdoc', 'Nargis\tRashid.gdoc', 'James\tFrancis.gdoc', 'Jordan\tMurray.gdoc', 'Tara\tKuhner.gdoc', 'Alessa\tPerkins.gdoc', 'Erica\tBowen.gdoc', 'ZHEN\tLI.gdoc', 'SUKANYA\tCHAKRABORTY.gdoc', 'Greg\tHerrera Jr.gdoc', 'cloud_performance_features.csv', 'Looking Through Good & Bad Examples.mp4', 'Premier_League_Model', 'download_copy.pdf']

In [44]:
project_dir = '/content/drive/MyDrive/Premier_League_Model'

print(os.listdir(project_dir))

['datasets', 'data', 'models', 'predictions', 'outputs']

In [46]:
datasets_dir = os.path.join(project_dir, 'datasets')

print(os.listdir(datasets_dir))

['2122.csv', '2223.csv', '2324.csv', '2425.csv', '2526.csv']

In [47]:
import os
import shutil

historical_dir = os.path.join(project_dir, 'Historical')

# Create Historical folder if it doesn't exist
os.makedirs(historical_dir, exist_ok=True)

# Copy all CSV files from datasets to Historical
for file in os.listdir(datasets_dir):
    if file.endswith('.csv'):
        shutil.copy2(
            os.path.join(datasets_dir, file),
            os.path.join(historical_dir, file)
        )

print("Historical files:")
print(os.listdir(historical_dir))

Historical files:
['2122.csv', '2223.csv', '2324.csv', '2425.csv', '2526.csv']

In [48]:
import pandas as pd
import os

seasons = ['2122.csv', '2223.csv', '2324.csv', '2425.csv', '2526.csv']

dfs = []

for file in seasons:
    path = os.path.join(historical_dir, file)
    df = pd.read_csv(path)
    df['Season'] = file.replace('.csv', '')
    dfs.append(df)

historical_df = pd.concat(dfs, ignore_index=True)

print("Total matches:", len(historical_df))
print("Columns:")
print(historical_df.columns.tolist())

Total matches: 1900
Columns:
['Div', 'Date', 'Time', 'HomeTeam', 'AwayTeam', 'FTHG', 'FTAG', 'FTR', 'HTHG', 'HTAG', 'HTR', 'Referee', 'HS', 'AS', 'HST', 'AST', 'HF', 'AF', 'HC', 'AC', 'HY', 'AY', 'HR', 'AR', 'B365H', 'B365D', 'B365A', 'BWH', 'BWD', 'BWA', 'IWH', 'IWD', 'IWA', 'PSH', 'PSD', 'PSA', 'WHH', 'WHD', 'WHA', 'VCH', 'VCD', 'VCA', 'MaxH', 'MaxD', 'MaxA', 'AvgH', 'AvgD', 'AvgA', 'B365>2.5', 'B365<2.5', 'P>2.5', 'P<2.5', 'Max>2.5', 'Max<2.5', 'Avg>2.5', 'Avg<2.5', 'AHh', 'B365AHH', 'B365AHA', 'PAHH', 'PAHA', 'MaxAHH', 'MaxAHA', 'AvgAHH', 'AvgAHA', 'B365CH', 'B365CD', 'B365CA', 'BWCH', 'BWCD', 'BWCA', 'IWCH', 'IWCD', 'IWCA', 'PSCH', 'PSCD', 'PSCA', 'WHCH', 'WHCD', 'WHCA', 'VCCH', 'VCCD', 'VCCA', 'MaxCH', 'MaxCD', 'MaxCA', 'AvgCH', 'AvgCD', 'AvgCA', 'B365C>2.5', 'B365C<2.5', 'PC>2.5', 'PC<2.5', 'MaxC>2.5', 'MaxC<2.5', 'AvgC>2.5', 'AvgC<2.5', 'AHCh', 'B365CAHH', 'B365CAHA', 'PCAHH', 'PCAHA', 'MaxCAHH', 'MaxCAHA', 'AvgCAHH', 'AvgCAHA', 'Season', 'BFH', 'BFD', 'BFA', '1XBH', '1XBD', '1XBA', 'BFEH', 'BFED', 'BFEA', 'BFE>2.5', 'BFE<2.5', 'BFEAHH', 'BFEAHA', 'BFCH', 'BFCD', 'BFCA', '1XBCH', '1XBCD', '1XBCA', 'BFECH', 'BFECD', 'BFECA', 'BFEC>2.5', 'BFEC<2.5', 'BFECAHH', 'BFECAHA', 'BFDH', 'BFDD', 'BFDA', 'BMGMH', 'BMGMD', 'BMGMA', 'BVH', 'BVD', 'BVA', 'CLH', 'CLD', 'CLA', 'LBH', 'LBD', 'LBA', 'BFDCH', 'BFDCD', 'BFDCA', 'BMGMCH', 'BMGMCD', 'BMGMCA', 'BVCH', 'BVCD', 'BVCA', 'CLCH', 'CLCD', 'CLCA', 'LBCH', 'LBCD', 'LBCA']

In [49]:
historical_df.head()

,Div,Date,Time,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,HTAG,...,BMGMCA,BVCH,BVCD,BVCA,CLCH,CLCD,CLCA,LBCH,LBCD,LBCA
0,E0,13/08/2021,20:00,Brentford,Arsenal,2,0,H,1,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,E0,14/08/2021,12:30,Man United,Leeds,5,1,H,1,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,E0,14/08/2021,15:00,Burnley,Brighton,1,2,A,1,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,E0,14/08/2021,15:00,Chelsea,Crystal Palace,3,0,H,2,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,E0,14/08/2021,15:00,Everton,Southampton,3,1,H,0,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [50]:
print(historical_df.isnull().sum())

Div            0
Date           0
Time           0
HomeTeam       0
AwayTeam       0
            ...
CLCD        1640
CLCA        1640
LBCH        1619
LBCD        1619
LBCA        1619
Length: 163, dtype: int64

In [51]:
print(historical_df.columns.tolist())

['Div', 'Date', 'Time', 'HomeTeam', 'AwayTeam', 'FTHG', 'FTAG', 'FTR', 'HTHG', 'HTAG', 'HTR', 'Referee', 'HS', 'AS', 'HST', 'AST', 'HF', 'AF', 'HC', 'AC', 'HY', 'AY', 'HR', 'AR', 'B365H', 'B365D', 'B365A', 'BWH', 'BWD', 'BWA', 'IWH', 'IWD', 'IWA', 'PSH', 'PSD', 'PSA', 'WHH', 'WHD', 'WHA', 'VCH', 'VCD', 'VCA', 'MaxH', 'MaxD', 'MaxA', 'AvgH', 'AvgD', 'AvgA', 'B365>2.5', 'B365<2.5', 'P>2.5', 'P<2.5', 'Max>2.5', 'Max<2.5', 'Avg>2.5', 'Avg<2.5', 'AHh', 'B365AHH', 'B365AHA', 'PAHH', 'PAHA', 'MaxAHH', 'MaxAHA', 'AvgAHH', 'AvgAHA', 'B365CH', 'B365CD', 'B365CA', 'BWCH', 'BWCD', 'BWCA', 'IWCH', 'IWCD', 'IWCA', 'PSCH', 'PSCD', 'PSCA', 'WHCH', 'WHCD', 'WHCA', 'VCCH', 'VCCD', 'VCCA', 'MaxCH', 'MaxCD', 'MaxCA', 'AvgCH', 'AvgCD', 'AvgCA', 'B365C>2.5', 'B365C<2.5', 'PC>2.5', 'PC<2.5', 'MaxC>2.5', 'MaxC<2.5', 'AvgC>2.5', 'AvgC<2.5', 'AHCh', 'B365CAHH', 'B365CAHA', 'PCAHH', 'PCAHA', 'MaxCAHH', 'MaxCAHA', 'AvgCAHH', 'AvgCAHA', 'Season', 'BFH', 'BFD', 'BFA', '1XBH', '1XBD', '1XBA', 'BFEH', 'BFED', 'BFEA', 'BFE>2.5', 'BFE<2.5', 'BFEAHH', 'BFEAHA', 'BFCH', 'BFCD', 'BFCA', '1XBCH', '1XBCD', '1XBCA', 'BFECH', 'BFECD', 'BFECA', 'BFEC>2.5', 'BFEC<2.5', 'BFECAHH', 'BFECAHA', 'BFDH', 'BFDD', 'BFDA', 'BMGMH', 'BMGMD', 'BMGMA', 'BVH', 'BVD', 'BVA', 'CLH', 'CLD', 'CLA', 'LBH', 'LBD', 'LBA', 'BFDCH', 'BFDCD', 'BFDCA', 'BMGMCH', 'BMGMCD', 'BMGMCA', 'BVCH', 'BVCD', 'BVCA', 'CLCH', 'CLCD', 'CLCA', 'LBCH', 'LBCD', 'LBCA']

In [52]:
print(historical_df[['Date', 'HomeTeam', 'AwayTeam', 'FTHG', 'FTAG', 'FTR']].head(10))

         Date    HomeTeam        AwayTeam  FTHG  FTAG FTR
0  13/08/2021   Brentford         Arsenal     2     0   H
1  14/08/2021  Man United           Leeds     5     1   H
2  14/08/2021     Burnley        Brighton     1     2   A
3  14/08/2021     Chelsea  Crystal Palace     3     0   H
4  14/08/2021     Everton     Southampton     3     1   H
5  14/08/2021   Leicester          Wolves     1     0   H
6  14/08/2021     Watford     Aston Villa     3     2   H
7  14/08/2021     Norwich       Liverpool     0     3   A
8  15/08/2021   Newcastle        West Ham     2     4   A
9  15/08/2021   Tottenham        Man City     1     0   H

In [53]:
print(historical_df[['Date', 'HomeTeam', 'AwayTeam', 'FTHG', 'FTAG', 'FTR']].tail(10))

            Date        HomeTeam     AwayTeam  FTHG  FTAG FTR
1890  24/05/2026        Brighton   Man United     0     3   A
1891  24/05/2026         Burnley       Wolves     1     1   D
1892  24/05/2026  Crystal Palace      Arsenal     1     2   A
1893  24/05/2026          Fulham    Newcastle     2     0   H
1894  24/05/2026       Liverpool    Brentford     1     1   D
1895  24/05/2026        Man City  Aston Villa     1     2   A
1896  24/05/2026   Nott'm Forest  Bournemouth     1     1   D
1897  24/05/2026      Sunderland      Chelsea     2     1   H
1898  24/05/2026       Tottenham      Everton     1     0   H
1899  24/05/2026        West Ham        Leeds     3     0   H

In [54]:
historical_df['Date'] = pd.to_datetime(
    historical_df['Date'],
    dayfirst=True,
    errors='coerce'
)

historical_df = historical_df.sort_values('Date').reset_index(drop=True)

print(historical_df[['Date', 'HomeTeam', 'AwayTeam', 'FTHG', 'FTAG', 'FTR']].head())
print(historical_df[['Date', 'HomeTeam', 'AwayTeam', 'FTHG', 'FTAG', 'FTR']].tail())

        Date    HomeTeam        AwayTeam  FTHG  FTAG FTR
0 2021-08-13   Brentford         Arsenal     2     0   H
1 2021-08-14  Man United           Leeds     5     1   H
2 2021-08-14     Burnley        Brighton     1     2   A
3 2021-08-14     Chelsea  Crystal Palace     3     0   H
4 2021-08-14     Everton     Southampton     3     1   H
           Date        HomeTeam    AwayTeam  FTHG  FTAG FTR
1895 2026-05-24  Crystal Palace     Arsenal     1     2   A
1896 2026-05-24         Burnley      Wolves     1     1   D
1897 2026-05-24        Brighton  Man United     0     3   A
1898 2026-05-24          Fulham   Newcastle     2     0   H
1899 2026-05-24        West Ham       Leeds     3     0   H

In [55]:
teams = sorted(
    set(historical_df['HomeTeam']) |
    set(historical_df['AwayTeam'])
)

print("Number of teams:", len(teams))
print(teams)

Number of teams: 27
['Arsenal', 'Aston Villa', 'Bournemouth', 'Brentford', 'Brighton', 'Burnley', 'Chelsea', 'Crystal Palace', 'Everton', 'Fulham', 'Ipswich', 'Leeds', 'Leicester', 'Liverpool', 'Luton', 'Man City', 'Man United', 'Newcastle', 'Norwich', "Nott'm Forest", 'Sheffield United', 'Southampton', 'Sunderland', 'Tottenham', 'Watford', 'West Ham', 'Wolves']

In [56]:
duplicates = historical_df.duplicated(
    subset=['Date', 'HomeTeam', 'AwayTeam']
).sum()

print("Duplicate matches:", duplicates)

Duplicate matches: 0

In [57]:
# Make a copy
matches = historical_df.copy()

# Make sure dates are datetime
matches['Date'] = pd.to_datetime(
    matches['Date'],
    dayfirst=True,
    errors='coerce'
)

# Sort chronologically
matches = matches.sort_values(
    ['Date', 'Time']
).reset_index(drop=True)

# Remove rows without a result
matches = matches.dropna(
    subset=['HomeTeam', 'AwayTeam', 'FTHG', 'FTAG', 'FTR']
).reset_index(drop=True)

print("Matches:", len(matches))
print(matches[['Date', 'HomeTeam', 'AwayTeam', 'FTHG', 'FTAG', 'FTR']].head())

Matches: 1900
        Date    HomeTeam        AwayTeam  FTHG  FTAG FTR
0 2021-08-13   Brentford         Arsenal     2     0   H
1 2021-08-14  Man United           Leeds     5     1   H
2 2021-08-14     Burnley        Brighton     1     2   A
3 2021-08-14     Chelsea  Crystal Palace     3     0   H
4 2021-08-14     Everton     Southampton     3     1   H

In [58]:
def get_result_for_team(goals_for, goals_against):
    if goals_for > goals_against:
        return 'W'
    elif goals_for < goals_against:
        return 'L'
    else:
        return 'D'


def get_points(goals_for, goals_against):
    if goals_for > goals_against:
        return 3
    elif goals_for == goals_against:
        return 1
    else:
        return 0

In [59]:
from collections import defaultdict, deque

def calculate_form(history, n=5):
    """
    Calculate recent form using up to the last n matches.
    Works even when a team has fewer than n matches.
    """

    if len(history) == 0:
        return {
            'matches': 0,
            'wins': 0,
            'draws': 0,
            'losses': 0,
            'points': 0,
            'goals_for': 0,
            'goals_against': 0
        }

    recent = list(history)[-n:]

    wins = sum(1 for x in recent if x['result'] == 'W')
    draws = sum(1 for x in recent if x['result'] == 'D')
    losses = sum(1 for x in recent if x['result'] == 'L')

    points = sum(x['points'] for x in recent)

    goals_for = sum(x['goals_for'] for x in recent)
    goals_against = sum(x['goals_against'] for x in recent)

    return {
        'matches': len(recent),
        'wins': wins,
        'draws': draws,
        'losses': losses,
        'points': points,
        'goals_for': goals_for,
        'goals_against': goals_against
    }

In [60]:
overall_history = defaultdict(lambda: deque(maxlen=20))
home_history = defaultdict(lambda: deque(maxlen=20))
away_history = defaultdict(lambda: deque(maxlen=20))

In [61]:
print("Teams currently found:")

teams = set(matches['HomeTeam']) | set(matches['AwayTeam'])

print("Number of teams:", len(teams))
print(sorted(teams))

Teams currently found:
Number of teams: 27
['Arsenal', 'Aston Villa', 'Bournemouth', 'Brentford', 'Brighton', 'Burnley', 'Chelsea', 'Crystal Palace', 'Everton', 'Fulham', 'Ipswich', 'Leeds', 'Leicester', 'Liverpool', 'Luton', 'Man City', 'Man United', 'Newcastle', 'Norwich', "Nott'm Forest", 'Sheffield United', 'Southampton', 'Sunderland', 'Tottenham', 'Watford', 'West Ham', 'Wolves']

In [62]:
from collections import defaultdict, deque
import numpy as np

# ---------------------------------------
# RESET HISTORIES
# ---------------------------------------

overall_history = defaultdict(lambda: deque(maxlen=20))
home_history = defaultdict(lambda: deque(maxlen=20))
away_history = defaultdict(lambda: deque(maxlen=20))

# ---------------------------------------
# ELO SETTINGS
# ---------------------------------------

DEFAULT_ELO = 1500
K_FACTOR = 20
HOME_ADVANTAGE = 60

elo = defaultdict(lambda: DEFAULT_ELO)


# ---------------------------------------
# FORM FUNCTION
# ---------------------------------------

def get_form(history, n=5):

    recent = list(history)[-n:]

    if len(recent) == 0:
        return {
            'matches': 0,
            'wins': 0,
            'draws': 0,
            'losses': 0,
            'points': 0,
            'goals_for': 0,
            'goals_against': 0
        }

    wins = sum(x['result'] == 'W' for x in recent)
    draws = sum(x['result'] == 'D' for x in recent)
    losses = sum(x['result'] == 'L' for x in recent)

    points = sum(x['points'] for x in recent)

    goals_for = sum(x['goals_for'] for x in recent)
    goals_against = sum(x['goals_against'] for x in recent)

    return {
        'matches': len(recent),
        'wins': wins,
        'draws': draws,
        'losses': losses,
        'points': points,
        'goals_for': goals_for,
        'goals_against': goals_against
    }


# ---------------------------------------
# FEATURE STORAGE
# ---------------------------------------

feature_rows = []


# ---------------------------------------
# PROCESS MATCHES CHRONOLOGICALLY
# ---------------------------------------

for _, match in matches.iterrows():

    home = match['HomeTeam']
    away = match['AwayTeam']

    # ===================================
    # 1. GET INFORMATION BEFORE MATCH
    # ===================================

    home_overall = get_form(overall_history[home], 5)
    away_overall = get_form(overall_history[away], 5)

    home_home = get_form(home_history[home], 5)
    away_away = get_form(away_history[away], 5)

    # ===================================
    # 2. ELO BEFORE MATCH
    # ===================================

    home_elo = elo[home]
    away_elo = elo[away]

    elo_difference = (
        home_elo + HOME_ADVANTAGE
    ) - away_elo

    # ===================================
    # 3. CREATE FEATURE ROW
    # ===================================

    row = {

        # Match information
        'Date': match['Date'],
        'HomeTeam': home,
        'AwayTeam': away,

        # -------------------------------
        # HOME OVERALL FORM
        # -------------------------------

        'Home_Last5_Matches':
            home_overall['matches'],

        'Home_Last5_Wins':
            home_overall['wins'],

        'Home_Last5_Draws':
            home_overall['draws'],

        'Home_Last5_Losses':
            home_overall['losses'],

        'Home_Last5_Points':
            home_overall['points'],

        'Home_Last5_GF':
            home_overall['goals_for'],

        'Home_Last5_GA':
            home_overall['goals_against'],


        # -------------------------------
        # AWAY OVERALL FORM
        # -------------------------------

        'Away_Last5_Matches':
            away_overall['matches'],

        'Away_Last5_Wins':
            away_overall['wins'],

        'Away_Last5_Draws':
            away_overall['draws'],

        'Away_Last5_Losses':
            away_overall['losses'],

        'Away_Last5_Points':
            away_overall['points'],

        'Away_Last5_GF':
            away_overall['goals_for'],

        'Away_Last5_GA':
            away_overall['goals_against'],


        # -------------------------------
        # HOME TEAM HOME FORM
        # -------------------------------

        'Home_Last5_Home_Matches':
            home_home['matches'],

        'Home_Last5_Home_Wins':
            home_home['wins'],

        'Home_Last5_Home_Draws':
            home_home['draws'],

        'Home_Last5_Home_Losses':
            home_home['losses'],

        'Home_Last5_Home_Points':
            home_home['points'],

        'Home_Last5_Home_GF':
            home_home['goals_for'],

        'Home_Last5_Home_GA':
            home_home['goals_against'],


        # -------------------------------
        # AWAY TEAM AWAY FORM
        # -------------------------------

        'Away_Last5_Away_Matches':
            away_away['matches'],

        'Away_Last5_Away_Wins':
            away_away['wins'],

        'Away_Last5_Away_Draws':
            away_away['draws'],

        'Away_Last5_Away_Losses':
            away_away['losses'],

        'Away_Last5_Away_Points':
            away_away['points'],

        'Away_Last5_Away_GF':
            away_away['goals_for'],

        'Away_Last5_Away_GA':
            away_away['goals_against'],


        # -------------------------------
        # ELO
        # -------------------------------

        'Home_Elo':
            home_elo,

        'Away_Elo':
            away_elo,

        'Elo_Difference':
            elo_difference,


        # -------------------------------
        # TARGETS
        # -------------------------------

        'FTHG':
            match['FTHG'],

        'FTAG':
            match['FTAG'],

        'FTR':
            match['FTR']
    }

    feature_rows.append(row)


    # ===================================
    # 4. UPDATE HISTORY AFTER MATCH
    # ===================================

    home_goals = match['FTHG']
    away_goals = match['FTAG']

    # Determine results
    if home_goals > away_goals:
        home_result = 'W'
        away_result = 'L'

    elif home_goals < away_goals:
        home_result = 'L'
        away_result = 'W'

    else:
        home_result = 'D'
        away_result = 'D'


    home_points = get_points(
        home_goals,
        away_goals
    )

    away_points = get_points(
        away_goals,
        home_goals
    )


    # Home team record
    home_record = {
        'result': home_result,
        'points': home_points,
        'goals_for': home_goals,
        'goals_against': away_goals
    }

    # Away team record
    away_record = {
        'result': away_result,
        'points': away_points,
        'goals_for': away_goals,
        'goals_against': home_goals
    }


    # Update overall
    overall_history[home].append(home_record)
    overall_history[away].append(away_record)

    # Update home / away histories
    home_history[home].append(home_record)
    away_history[away].append(away_record)


    # ===================================
    # 5. UPDATE ELO
    # ===================================

    home_rating = elo[home]
    away_rating = elo[away]

    expected_home = 1 / (
        1 + 10 ** (
            (away_rating - (home_rating + HOME_ADVANTAGE))
            / 400
        )
    )

    if home_result == 'W':
        actual_home = 1
    elif home_result == 'D':
        actual_home = 0.5
    else:
        actual_home = 0


    elo_change = K_FACTOR * (
        actual_home - expected_home
    )

    elo[home] += elo_change
    elo[away] -= elo_change


# ---------------------------------------
# CREATE DATAFRAME
# ---------------------------------------

features_df = pd.DataFrame(feature_rows)

print("Feature dataset shape:", features_df.shape)

features_df.head()

Feature dataset shape: (1900, 37)

,Date,HomeTeam,AwayTeam,Home_Last5_Matches,Home_Last5_Wins,Home_Last5_Draws,Home_Last5_Losses,Home_Last5_Points,Home_Last5_GF,Home_Last5_GA,...,Away_Last5_Away_Losses,Away_Last5_Away_Points,Away_Last5_Away_GF,Away_Last5_Away_GA,Home_Elo,Away_Elo,Elo_Difference,FTHG,FTAG,FTR
0,2021-08-13,Brentford,Arsenal,0,0,0,0,0,0,0,...,0,0,0,0,1500.0,1500.0,60.0,2,0,H
1,2021-08-14,Man United,Leeds,0,0,0,0,0,0,0,...,0,0,0,0,1500.0,1500.0,60.0,5,1,H
2,2021-08-14,Burnley,Brighton,0,0,0,0,0,0,0,...,0,0,0,0,1500.0,1500.0,60.0,1,2,A
3,2021-08-14,Chelsea,Crystal Palace,0,0,0,0,0,0,0,...,0,0,0,0,1500.0,1500.0,60.0,3,0,H
4,2021-08-14,Everton,Southampton,0,0,0,0,0,0,0,...,0,0,0,0,1500.0,1500.0,60.0,3,1,H

In [63]:
features_df[
    [
        'Date',
        'HomeTeam',
        'AwayTeam',
        'Home_Last5_Matches',
        'Away_Last5_Matches',
        'Home_Last5_Points',
        'Away_Last5_Points',
        'Home_Elo',
        'Away_Elo',
        'Elo_Difference',
        'FTR'
    ]
].head(15)

,Date,HomeTeam,AwayTeam,Home_Last5_Matches,Away_Last5_Matches,Home_Last5_Points,Away_Last5_Points,Home_Elo,Away_Elo,Elo_Difference,FTR
0,2021-08-13,Brentford,Arsenal,0,0,0,0,1500.000000,1500.000000,60.000000,H
1,2021-08-14,Man United,Leeds,0,0,0,0,1500.000000,1500.000000,60.000000,H
2,2021-08-14,Burnley,Brighton,0,0,0,0,1500.000000,1500.000000,60.000000,A
3,2021-08-14,Chelsea,Crystal Palace,0,0,0,0,1500.000000,1500.000000,60.000000,H
4,2021-08-14,Everton,Southampton,0,0,0,0,1500.000000,1500.000000,60.000000,H
5,2021-08-14,Leicester,Wolves,0,0,0,0,1500.000000,1500.000000,60.000000,H
6,2021-08-14,Watford,Aston Villa,0,0,0,0,1500.000000,1500.000000,60.000000,H
7,2021-08-14,Norwich,Liverpool,0,0,0,0,1500.000000,1500.000000,60.000000,A
8,2021-08-15,Newcastle,West Ham,0,0,0,0,1500.000000,1500.000000,60.000000,A
9,2021-08-15,Tottenham,Man City,0,0,0,0,1500.000000,1500.000000,60.000000,H
10,2021-08-21,Liverpool,Burnley,1,1,3,0,1511.709974,1488.290026,83.419947,H
11,2021-08-21,Man City,Norwich,1,1,0,0,1491.709974,1488.290026,63.419947,H
12,2021-08-21,Leeds,Everton,1,1,0,3,1491.709974,1508.290026,43.419947,D
13,2021-08-21,Aston Villa,Newcastle,1,1,0,0,1491.709974,1488.290026,63.419947,H
14,2021-08-21,Crystal Palace,Brentford,1,1,0,3,1491.709974,1508.290026,43.419947,D

In [64]:
features_df[
    [
        'Date',
        'HomeTeam',
        'AwayTeam',
        'Home_Last5_Matches',
        'Away_Last5_Matches',
        'Home_Last5_Points',
        'Away_Last5_Points',
        'Home_Elo',
        'Away_Elo',
        'Elo_Difference',
        'FTR'
    ]
].iloc[1000:1010]

,Date,HomeTeam,AwayTeam,Home_Last5_Matches,Away_Last5_Matches,Home_Last5_Points,Away_Last5_Points,Home_Elo,Away_Elo,Elo_Difference,FTR
1000,2024-02-17,Burnley,Arsenal,5,5,2,12,1385.080617,1674.784391,-229.703774,A
1001,2024-02-17,Fulham,Aston Villa,5,5,8,7,1486.962163,1588.468622,-41.506460,A
1002,2024-02-17,Newcastle,Bournemouth,5,5,7,2,1573.850154,1468.696441,165.153713,D
1003,2024-02-17,Nott'm Forest,West Ham,5,5,4,3,1433.201820,1507.875931,-14.674111,H
1004,2024-02-17,Man City,Chelsea,5,5,15,9,1730.223588,1512.558926,277.664662,D
1005,2024-02-18,Sheffield United,Brighton,5,5,4,5,1417.734493,1544.738888,-67.004395,A
1006,2024-02-18,Luton,Man United,5,5,5,10,1456.467011,1603.977230,-87.510219,A
1007,2024-02-19,Everton,Crystal Palace,5,5,3,6,1468.580355,1455.597927,72.982428,D
1008,2024-02-20,Man City,Brentford,5,5,13,6,1723.587789,1488.014511,295.573278,H
1009,2024-02-21,Liverpool,Luton,5,5,12,5,1697.406296,1448.933812,308.472485,H

In [65]:
# Add goal-rate features

features_df['Home_Last5_GF_Avg'] = (
    features_df['Home_Last5_GF'] /
    features_df['Home_Last5_Matches'].replace(0, np.nan)
)

features_df['Home_Last5_GA_Avg'] = (
    features_df['Home_Last5_GA'] /
    features_df['Home_Last5_Matches'].replace(0, np.nan)
)

features_df['Away_Last5_GF_Avg'] = (
    features_df['Away_Last5_GF'] /
    features_df['Away_Last5_Matches'].replace(0, np.nan)
)

features_df['Away_Last5_GA_Avg'] = (
    features_df['Away_Last5_GA'] /
    features_df['Away_Last5_Matches'].replace(0, np.nan)
)


# Home-specific averages

features_df['Home_Last5_Home_GF_Avg'] = (
    features_df['Home_Last5_Home_GF'] /
    features_df['Home_Last5_Home_Matches'].replace(0, np.nan)
)

features_df['Home_Last5_Home_GA_Avg'] = (
    features_df['Home_Last5_Home_GA'] /
    features_df['Home_Last5_Home_Matches'].replace(0, np.nan)
)


# Away-specific averages

features_df['Away_Last5_Away_GF_Avg'] = (
    features_df['Away_Last5_Away_GF'] /
    features_df['Away_Last5_Away_Matches'].replace(0, np.nan)
)

features_df['Away_Last5_Away_GA_Avg'] = (
    features_df['Away_Last5_Away_GA'] /
    features_df['Away_Last5_Away_Matches'].replace(0, np.nan)
)


# Replace missing values for teams with no previous matches
goal_rate_columns = [
    'Home_Last5_GF_Avg',
    'Home_Last5_GA_Avg',
    'Away_Last5_GF_Avg',
    'Away_Last5_GA_Avg',
    'Home_Last5_Home_GF_Avg',
    'Home_Last5_Home_GA_Avg',
    'Away_Last5_Away_GF_Avg',
    'Away_Last5_Away_GA_Avg'
]

features_df[goal_rate_columns] = (
    features_df[goal_rate_columns]
    .fillna(0)
)

print(features_df[goal_rate_columns].head(10))

   Home_Last5_GF_Avg  Home_Last5_GA_Avg  Away_Last5_GF_Avg  Away_Last5_GA_Avg  \
0                0.0                0.0                0.0                0.0
1                0.0                0.0                0.0                0.0
2                0.0                0.0                0.0                0.0
3                0.0                0.0                0.0                0.0
4                0.0                0.0                0.0                0.0
5                0.0                0.0                0.0                0.0
6                0.0                0.0                0.0                0.0
7                0.0                0.0                0.0                0.0
8                0.0                0.0                0.0                0.0
9                0.0                0.0                0.0                0.0

   Home_Last5_Home_GF_Avg  Home_Last5_Home_GA_Avg  Away_Last5_Away_GF_Avg  \
0                     0.0                     0.0                     0.0
1                     0.0                     0.0                     0.0
2                     0.0                     0.0                     0.0
3                     0.0                     0.0                     0.0
4                     0.0                     0.0                     0.0
5                     0.0                     0.0                     0.0
6                     0.0                     0.0                     0.0
7                     0.0                     0.0                     0.0
8                     0.0                     0.0                     0.0
9                     0.0                     0.0                     0.0

   Away_Last5_Away_GA_Avg
0                     0.0
1                     0.0
2                     0.0
3                     0.0
4                     0.0
5                     0.0
6                     0.0
7                     0.0
8                     0.0
9                     0.0

In [66]:
features_df['Form_Points_Difference'] = (
    features_df['Home_Last5_Points'] -
    features_df['Away_Last5_Points']
)

features_df['Goals_For_Difference'] = (
    features_df['Home_Last5_GF_Avg'] -
    features_df['Away_Last5_GF_Avg']
)

features_df['Goals_Against_Difference'] = (
    features_df['Home_Last5_GA_Avg'] -
    features_df['Away_Last5_GA_Avg']
)

features_df['Home_Form_Difference'] = (
    features_df['Home_Last5_Home_Points'] -
    features_df['Away_Last5_Away_Points']
)

features_df['Attack_Difference'] = (
    features_df['Home_Last5_Home_GF_Avg'] -
    features_df['Away_Last5_Away_GF_Avg']
)

features_df['Defense_Difference'] = (
    features_df['Away_Last5_Away_GA_Avg'] -
    features_df['Home_Last5_Home_GA_Avg']
)

In [67]:
features_df['Over_0.5'] = (
    (features_df['FTHG'] + features_df['FTAG']) > 0
).astype(int)

In [ ]:
features_df['Over_1.5'] = (
    (features_df['FTHG'] + features_df['FTAG']) > 1
).astype(int)

In [68]:
features_df['Over_3.5'] = (
    (features_df['FTHG'] + features_df['FTAG']) > 3
).astype(int)

In [69]:
features_df['BTTS'] = (
    (features_df['FTHG'] > 0) &
    (features_df['FTAG'] > 0)
).astype(int)

In [70]:
features_df['Score'] = (
    features_df['FTHG'].astype(int).astype(str)
    + '-'
    + features_df['FTAG'].astype(int).astype(str)
)

print(features_df['Score'].value_counts().head(20))

Score
1-1    210
2-1    160
1-0    156
0-1    129
2-0    128
1-2    126
2-2    124
0-2    103
0-0     99
3-1     98
3-0     89
1-3     53
0-3     51
3-2     51
2-3     43
4-1     41
4-0     30
1-4     29
0-4     22
4-2     20
Name: count, dtype: int64